### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by apetersson** [mitchellcash/Jaxx-Codebase#1]
I wasn't aware jaxx did not host the source properly. Thanks for your efforts. Did you attempt to build the run from these sources? Are there build instructions somewhere?

**Comment by MitchellCash** [comment]
@apetersson unfortunately as Jaxx only release their back end codebase and not any of the third party libraries or UI elements, actually building this is not possible in its current state.

Rather than being able to build the software, I have placed this here more for the ability to clearly see their back end code changes between commits and also code security audit/review.
